version: "3"
services:
  text_classification:
    image: datascience-notebook
    container_name: text_classification
    user: root
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "443:8888"
    volumes:
      - ../work:/home/jovyan/
    restart: unless-stopped
    stdin_open: true
    command: jupyter notebook --port 8888 --NotebookApp.token='' --ip=0.0.0.0 --allow-root 
